"""Write shard configs for the 10 GB bumpy-terrain tire-force dataset.

Same excitation distribution as the flat 10 GB tire-force set (which mirrors
the 300 GB pool): 4 shards rotating through the low/medium/fast/mixed speed
bands, 300g family mix, tire channels enabled. The difference is the terrain:

- `rigid_heightmap` patches built from the 100-map bumpy library
  (assets/bumpy_terrain/bumpy_field_NNN.bmp, 256x256 grayscale, gray 128 =
  ground, heights in [-0.6, 0.6] m, flat spawn disc at the center)
- each episode picks one of the 100 maps deterministically (hash of the
  episode id), recorded in the episode meta JSON
- the patch spans 500 x 500 m; episodes are truncated if the chassis crosses
  90% of the half-extent so wheels never leave the terrain mesh

The bumpy library is committed under assets/bumpy_terrain (about 7 MB), so a
plain git pull provides it everywhere. It was generated by (and is identical
to) the seeded generator in chrono/src/demos/python/vehicle/
demo_bumpy_surface.py (file NNN = seed NNN).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from prepare_hmmwv_300g_generation import base_config, family_config, family_counts, speed_band

SEED_BASE = 2026061200

TERRAIN = {
    "type": "rigid_heightmap",
    "height_map_dir": "assets/bumpy_terrain",
    "height_map_count": 100,
    "height_map_pattern": "bumpy_field_%03d.bmp",
    "length_m": 500.0,
    "width_m": 500.0,
    "height_min_m": -0.6,
    "height_max_m": 0.6,
    "keep_within_fraction": 0.9,
    "friction": 0.9,
    "restitution": 0.01,
    "young_modulus_pa": 20000000.0,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan-dir", type=Path, default=Path("artifacts/datasets/hmmwv_bumpy_10g_plan"))
    parser.add_argument("--output-root", type=Path, default=Path("artifacts/datasets/hmmwv_bumpy_10g_shards"))
    parser.add_argument("--num-shards", type=int, default=4)
    # ~75% of episodes truncate at the patch border, so episodes are shorter
    # than on the flat 500x500-unbounded set; 4 x 340 lands near 10 GB.
    parser.add_argument("--episodes-per-shard", type=int, default=340)
    parser.add_argument("--smoke-episodes", type=int, default=12)
    parser.add_argument(
        "--chrono-data-root",
        type=str,
        default=None,
        help="Override chrono data root (e.g. $CONDA_PREFIX/share/chrono/data on a cluster).",
    )
    return parser.parse_args()


def shard_config(
    shard_index: int,
    dataset_name: str,
    output_subdir: str,
    episodes: int,
    chrono_data_root: str | None,
) -> dict[str, Any]:
    cfg = base_config(dataset_name, output_subdir, seed=SEED_BASE + 17 * shard_index)
    cfg["logging"]["include_tire_channels"] = True
    cfg["terrain"] = dict(TERRAIN)
    if chrono_data_root:
        cfg["chrono_data_root"] = chrono_data_root
        cfg["vehicle_data_root"] = str(Path(chrono_data_root) / "vehicle")

    templates = {
        "multi_steer": "multi_steer",
        "sustained_turn": "step_steer",
        "sine_steer": "sine_steer",
        "chirp_steer": "chirp_steer",
        "doublet_steer": "doublet_steer",
        "steer_brake": "steer_brake",
    }
    band = speed_band(shard_index)
    families = []
    for family_name, count in family_counts(episodes).items():
        if count <= 0:
            continue
        family = family_config(shard_index, family_name, count, templates[family_name], band)
        family["scenario_prefix"] = f"b10_s{shard_index:03d}_{family_name}"
        families.append(family)
    cfg["scenario_generator"]["families"] = families
    return cfg


def main() -> int:
    args = parse_args()
    config_dir = args.plan_dir / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)
    args.output_root.mkdir(parents=True, exist_ok=True)

    manifest: list[dict[str, Any]] = []
    for shard_index in range(args.num_shards):
        dataset_name = f"hmmwv_bumpy_10g_s{shard_index:03d}"
        output_subdir = str(args.output_root / f"shard_{shard_index:03d}")
        cfg = shard_config(
            shard_index, dataset_name, output_subdir, args.episodes_per_shard, args.chrono_data_root
        )
        path = config_dir / f"shard_{shard_index:03d}.json"
        path.write_text(json.dumps(cfg, indent=2) + "\n")
        manifest.append(
            {
                "shard_index": shard_index,
                "dataset_name": dataset_name,
                "config_path": str(path),
                "output_subdir": output_subdir,
                "speed_band": speed_band(shard_index)["name"],
                "episodes": args.episodes_per_shard,
                "families": family_counts(args.episodes_per_shard),
            }
        )

    smoke_index = 3  # band rotation: 3 -> "mixed"
    smoke_cfg = shard_config(
        smoke_index,
        "hmmwv_bumpy_10g_smoke",
        str(args.output_root / "smoke"),
        args.smoke_episodes,
        args.chrono_data_root,
    )
    smoke_cfg["scenario_generator"]["seed"] = SEED_BASE + 9999
    smoke_cfg["scenario_generator"]["shuffle_seed"] = SEED_BASE + 10000
    for family in smoke_cfg["scenario_generator"]["families"]:
        family["scenario_prefix"] = family["scenario_prefix"].replace("b10_s003", "b10_smoke")
    (config_dir / "smoke.json").write_text(json.dumps(smoke_cfg, indent=2) + "\n")

    (args.plan_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {args.num_shards} shard configs + smoke config under {args.plan_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
