#!/bin/bash
# Orchestrator for plan §31 (user request 2026-09-07: automate the analysis and follow-up): waits for the augmentation runs
# (wp8c_*, wp8d_*) to be scored, applies the pre-registered verdict, launches the branch's follow-up, evaluates it, and
# leaves markers for the review step. Branches (notes §13.9):
#   PASS   -> tracker retrained inside the best augmented imagination (cluster, 2 seeds) + fresh sealed arenas on newton
#   B_FAIL -> tracker retrained inside the best augmented imagination (cluster, 2 seeds)
#   A_FAIL -> wave 4: events re-anchored on the momentum-loss moment + the best augmentation (cluster, 4 runs)
#   nohup scripts/traverse_wp8_followup.sh > /tmp/wp8_followup.log 2>&1 &
cd /home/harry/NeDM; export PYTHONPATH=src; PY=/home/harry/miniconda3/envs/nedm/bin/python
EVAL=artifacts/traverse/wp8_eval; REMOTE=amd:/work1/dannegrut/harry/nedm/artifacts/traverse
log() { echo "[$(date +%m-%d\ %H:%M)] $*"; }
# ---- stage 1: all augmentation runs scored
N_EXPECTED=12
until [ $(ls $EVAL/wp8c_*/done $EVAL/wp8d_*/done 2>/dev/null | wc -l) -ge $N_EXPECTED ]; do sleep 300; done
log "stage 1: $N_EXPECTED augmentation runs scored"
# ---- stage 2: verdict (re-scores runs lacking the AR probe; runs the tracker-in-the-loop decision test)
$PY scripts/traverse_wp8_verdict.py --runs 'wp8c_*' 'wp8d_*' > /tmp/wp8_verdict.log 2>&1 || { log "verdict failed"; cat /tmp/wp8_verdict.log | tail -5; exit 1; }
BRANCH=$($PY -c "import json; print(json.load(open('$EVAL/verdict.json'))['branch'])")
BEST=$($PY -c "import json; print(json.load(open('$EVAL/verdict.json'))['best'])")
log "stage 2: verdict $BRANCH, best run $BEST"; cat $EVAL/verdict.txt
CFG=artifacts/traverse/$BEST/config.json
AUG=$($PY -c "
import json; c=json.load(open('$CFG'))
print(f\"--action-noise {c.get('action_noise',0)} --action-noise-rho {c.get('action_noise_rho',0)} --action-smooth-p {c.get('action_smooth_p',0)}\")")
# ---- stage 3: branch follow-up
rsync -az scripts/traverse_wp2_train_map.py scripts/traverse_wp3_train_tracker.py amd:/work1/dannegrut/harry/nedm/scripts/
rsync -az src/nedm/traverse/tracker_env.py amd:/work1/dannegrut/harry/nedm/src/nedm/traverse/
rsync -az artifacts/traverse/wp7_cache_v1/events.json amd:/work1/dannegrut/harry/nedm/artifacts/traverse/wp7_cache_v1/events.json
rsync -az slurm/wp8_tracker.sbatch amd:/work1/dannegrut/harry/nedm/slurm/
JOBS=()
if [ "$BRANCH" = "A_FAIL" ]; then
  cat > slurm/wp8_launch4.sh <<EOS
#!/bin/bash
# Wave 4 (auto-generated by traverse_wp8_followup.sh): momentum-loss events + the best augmentation ($BEST: $AUG)
cd /work1/dannegrut/harry/nedm
INIT=artifacts/traverse/wp2_mapv2_pt_dag_ro8_amd/ckpt_best.pt
B="--init-from \$INIT --lr 3e-4 --min-lr 3e-5 --warmup-steps 500 --rollout-steps 80 --steps 6000 --event-frac 0.6 --progress-weight 1 --stall-eval-jitter 0.03 --event-kind-weights episodes $AUG"
sub() { local name=\$1; shift; sbatch -J \$name slurm/wp8_stall.sbatch \$name "\$@"; }
sub wp8e_mom       \$B --event-kinds approach launch matched momentum momentum momentum recovery stuck
sub wp8e_mom_s1    \$B --event-kinds approach launch matched momentum momentum momentum recovery stuck --seed 1
sub wp8e_mom_only  \$B --event-kinds launch matched momentum momentum momentum momentum
sub wp8e_mom_k120  \$B --event-kinds approach launch matched momentum momentum momentum recovery stuck --rollout-steps 120 --steps 5000
EOS
  rsync -az slurm/wp8_launch4.sh amd:/work1/dannegrut/harry/nedm/slurm/; ssh amd 'cd /work1/dannegrut/harry/nedm && bash slurm/wp8_launch4.sh' | grep -i "submitted" | wc -l
  JOBS=(wp8e_mom wp8e_mom_s1 wp8e_mom_only wp8e_mom_k120); log "wave 4 launched"
else
  ssh amd "cd /work1/dannegrut/harry/nedm && sbatch -J wp8_trk0 slurm/wp8_tracker.sbatch wp8_tracker_${BEST}_s0 artifacts/traverse/$BEST/ckpt_best.pt --max-iterations 1000 --seed 1 && sbatch -J wp8_trk1 slurm/wp8_tracker.sbatch wp8_tracker_${BEST}_s1 artifacts/traverse/$BEST/ckpt_best.pt --max-iterations 1000 --seed 2" | grep -i submitted
  JOBS=(wp8_tracker_${BEST}_s0 wp8_tracker_${BEST}_s1); log "tracker retraining launched inside $BEST"
  if [ "$BRANCH" = "PASS" ]; then scripts/traverse_wp8_sealed_prep.sh 1.25 > /tmp/wp8_sealed_prep.log 2>&1 && log "sealed prep launched" || log "sealed prep FAILED (see /tmp/wp8_sealed_prep.log)"; fi
fi
# ---- stage 4: wait for the follow-up jobs, pull, evaluate
for j in "${JOBS[@]}"; do
  until ssh amd "test -f /work1/dannegrut/harry/nedm/artifacts/traverse/$j/g3_readout.json -o -f /work1/dannegrut/harry/nedm/artifacts/traverse/$j/model_1000.pt -o -f /work1/dannegrut/harry/nedm/artifacts/traverse/$j/model_999.pt" 2>/dev/null; do
    [ -z "$(ssh amd "squeue -u \$USER -h -n $j" 2>/dev/null)" ] && ssh amd "test -d /work1/dannegrut/harry/nedm/artifacts/traverse/$j" 2>/dev/null && sleep 60 && break
    sleep 300
  done
  rsync -az $REMOTE/$j/ artifacts/traverse/$j/ 2>/dev/null; log "pulled $j"
done
if [ "$BRANCH" = "A_FAIL" ]; then
  # standard scoring of the wave-4 runs + a second verdict
  pgrep -f traverse_wp8_eval_runs.s[h] > /dev/null || nohup scripts/traverse_wp8_eval_runs.sh > /tmp/wp8_eval4.log 2>&1 &
  until [ $(ls $EVAL/wp8e_*/done 2>/dev/null | wc -l) -ge 4 ]; do sleep 300; done
  $PY scripts/traverse_wp8_verdict.py --runs 'wp8e_*' > /tmp/wp8_verdict4.log 2>&1; cp $EVAL/verdict.txt $EVAL/verdict_wave4.txt; cp $EVAL/verdict.json $EVAL/verdict_wave4.json
  log "wave 4 verdict:"; cat $EVAL/verdict_wave4.txt
else
  # the new tracker: decision test (tracker in the loop) and closed-loop stall tests with it, on the best model and the frozen one
  for j in "${JOBS[@]}"; do
    $PY -u scripts/traverse_wp7_stall_diagnosis.py decision --arenas arena_f105 --dynamics-checkpoints artifacts/traverse/$BEST/ckpt_best.pt artifacts/traverse/wp2_mapv2_pt_dag_ro8_amd/ckpt_best.pt --policy artifacts/traverse/$j --max-ladders 0 --tag trk_$j > $EVAL/decision_$j.log 2>&1
    $PY scripts/traverse_wp7_stall_diagnosis.py model --arenas arena_f105 --classes launch stop --dynamics-checkpoints artifacts/traverse/$BEST/ckpt_best.pt --policy artifacts/traverse/$j --tag trk_$j --roll-limit-deg 60 --pitch-limit-deg 60 > /dev/null 2>&1 \
      && $PY scripts/traverse_wp7_stall_diagnosis.py analyze --tag trk_$j --examples 0 > $EVAL/analyze_$j.txt 2>/dev/null
    rm -f artifacts/traverse/wp7_stall_diag/model_tests_trk_$j.json
    $PY scripts/traverse_wp7_imagine_cache.py --cache artifacts/traverse/wp7_cache_v1 --arenas arena_f105 --dynamics-checkpoints artifacts/traverse/$BEST/ckpt_best.pt --policy artifacts/traverse/$j --roll-limit-deg 60 --pitch-limit-deg 60 --out $EVAL/imagine_$j > /dev/null 2>&1
    $PY scripts/traverse_wp7_pick_table.py --cache artifacts/traverse/wp7_cache_v1 --arenas arena_f105 --imagine $j=$EVAL/imagine_$j/rows.json --json $EVAL/pick_$j.json > $EVAL/pick_$j.txt 2>&1
    log "evaluated tracker $j"; grep -E "\[tracker\]" $EVAL/decision_$j.log | head -4; grep "world model\|fastest" $EVAL/pick_$j.txt | head -3
  done
fi
log "FOLLOWUP DONE ($BRANCH)"
